// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'acpchat-reader-section-head-text'
  | 'acpchat-reader-section-sidenav-tooltip'
  | 'pref-agent-profiles'
  | 'pref-default-agent'
  | 'pref-default-preset'
  | 'pref-help'
  | 'pref-prompt-presets'
  | 'pref-session-store'
  | 'pref-template'
  | 'pref-title'
  | 'prefs-title';
