// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "agentProfiles": string;
      "defaultAgent": string;
      "sendKeyMode": string;
      "chatFontSizePx": string;
      "toolDetailsDefaultOpen": string;
      "sessionStorePath": string;
    };
  }
}
