// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "agentProfiles": string;
      "defaultAgent": string;
      "promptPresets": string;
      "defaultPresetId": string;
      "sessionStorePath": string;
      "defaultTemplate": string;
    };
  }
}
